### ISSUE TITLE
MGMT: Domains Landing Screen

### ISSUE THREAD

**Issue by tsschmidt** [Unicon/cas#25]
Add a new screen that lists Domains in a paginated table.  Selecting a Domain will navigate to the Services Screen that will only list the services that are part of that domain.

**Comment by tsschmidt** [comment]
Added this functionality as a new branch mgmt-domain-screen to keep it separate for now from fixes for other issues.   Take a look and see if you agree with this change.

**Comment by mmoayyed** [comment]
Are you sure you have pushed the branch? Not seeing it :(

**Comment by tsschmidt** [comment]
Yeah I pushed to my repo.  It is pushed here now.

**Comment by mmoayyed** [comment]
I think this is fine. Few minors:

1. Perhaps "Default" as opposed to "default"?
2. Do you envision adding other operations to the screen for a domain besides Edit? Because that's an extra click right now. 
3. Links to domains themselves don't actually change the mouse icon? When I over, the mouse icon changes to a text-edit type of cursor. 
4. I might give the "filter domains" search field a little bit more presence by making it larger and wider, but that possibly is just me nitpicking. 

Otherwise, very good.

**Comment by tsschmidt** [comment]
For number 2 above, I had planned to do "Details" option that would expand the row and show all the services under that domain.  Problem is the Data Table doesn't like to handle rows that change height, and it didn't look that good.  I mostly left it because I though the screen seemed sparse without it.  I am willing to get rid of it if that is the consensus

**Comment by tsschmidt** [comment]
Merged
