### ISSUE TITLE
MGMT: Page refresh causes app to become unavailable

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#35]
- Login into the app, and click "Add New Service"
- URL turns into `.../cas-management/form/-1`
- Simply refresh the browser.
- See:

> The CAS management webapp is unavailable.
> There was an error trying to complete your request. Please notify your support desk or try again.

**Comment by tsschmidt** [comment]
I am going to have to look in the Angular Router some more for this.   I think the best that can be done is to bring up the app fresh.

**Comment by tsschmidt** [comment]
It looks like the fix for this is going to be adding a forwarding controller that will send all unmapped urls back to manage.html.  I pushed mgmt-forward-controller with my lame attempt at this.  It works in that it refreshes the entire app.  I think there may be some routing changes we can do so it stays in place, but still researching.  Please take a look at the branch.  I setup a whole new controller for this functionality, but it seems like we should be able to do this with controllers that are already configured, I just not sure how or where.

**Comment by mmoayyed** [comment]
Cool. Thanks. Going to tag/ask @mindblender to review at the right time.

**Comment by tsschmidt** [comment]
Pushed changes to mgmt-router that fix this issue and cleans up the url parameters in the app.  You can also go directly to screens in the app by typing in the url bar.  For instance to start the app editing a new service you type https://server/cas-management/form/-1.

**Comment by mmoayyed** [comment]
Merged.
