### ISSUE TITLE
MGMT: Lint Angular ts 

### ISSUE THREAD

**Issue by tsschmidt** [Unicon/cas#63]
Clean up TypeScript files in the front end to conform to style standards.

**Comment by tsschmidt** [comment]
I finally got around to using the ng lint tool and cleaned up the front end files.  This is pushed to mgmt-lint and hopefully all the codacy errors will go away.

**Comment by mmoayyed** [comment]
Outstanding!

**Comment by tsschmidt** [comment]
I will merge in master and do another push

**Comment by mmoayyed** [comment]
Just to help you out a little bit, and others; turns out GH has the super nice ability to let one merge a PR with master on the UI so you dont have to!

![image](https://user-images.githubusercontent.com/1205228/32069906-860c6518-ba97-11e7-946e-4f43f5005e27.png)

Possible, if there are no conflicts found. Otherwise, I might ping you :)

**Comment by tsschmidt** [comment]
Cool.  Now tell me what "Jurgenizm" is.

________________________________

**Comment by mmoayyed** [comment]
Ah! :)

This is slang somewhat popular in Spring-based projects[?] based on the works of Jurgen Holler of Spring Framework. Legend has it that when folks introduced changes and features, Jurgen would go in a bit later and clean up style, documentation, code organization. The process became known as Jurgenizing code, short for "stuff that deals with code maintenance, refactoring and clean-up".

I cant find anything now, but I am quite sure there are whole talks on youtube dedicated to the same phenomena.

**Comment by mmoayyed** [comment]
This is merged.
