### ISSUE TITLE
MGMT: OIDC Client type points to OAuth

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#66]
See the image below:

![image](https://user-images.githubusercontent.com/1205228/32079611-3c6c4e02-bab8-11e7-8b26-c18ca2ae739e.png)

**Comment by tsschmidt** [comment]
For this screen I just re-used the OAuth Client options and then show the additional OIDC options below it.  I thought this would make sense since OIDC is an extension of OAuth.  Do you think this is confusing and I should just copy this into the OIDC form and a change the labels to be "OIDC Client ID" and such?

**Comment by mmoayyed** [comment]
> Do you think this is confusing and I should just copy this into the OIDC form...

Indeed, yes. I am certainly OK without it, but it's best to keep consistent...and of course, easier to not have to explain the relationship between OAuth and OIDC to novice deployers :)

**Comment by tsschmidt** [comment]
A fix has been pushed to mgmt-5.2-bugs
